name: use_conda

on: [push, pull_request]

jobs:
  use_conda:
    name: ${{ matrix.os }}_${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ['3.8', '3.11']

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: which_python
        shell: bash -el {0}
        run: which python

      - name: which_pip
        shell: bash -el {0}
        run: which pip

      - name: which_python3
        shell: bash -el {0}
        run: which python3

      - name: which_shell
        shell: bash -el {0}
        run: ps -p $$

      - name: conda_info
        shell: bash -el {0}
        run: |
          conda info
          conda list

